version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

executor:
  name: default
  python-version: 3.7.4
jobs:
  setupCLI:
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_SECRET_ACCESS_KEY
          aws-region: us-west-2
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          configure-default-region: us-west-2
          profile-name: augusto-circleCI
      - checkout
      - deploy:
          capabilities: CAPABILITY_NAMED_IAM
          stack-name: my_stack
          template-file-path: template.yml
workflows:
  my_workflow:
    jobs:
      - setupCLI
