version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

executor:
  name: default
  python-version: 3.7.4
jobs:
  setupCLI:
    docker:
      - image: amazon/aws-cli
    steps:
      - aws-cli/install
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack \
              --region=us-west-2 \
              --aws-access-key-id $AWS_ACCESS_KEY_ID \
              --aws-secret-access-key $AWS_SECRET_ACCESS_KEY \
              --capabilities CAPABILITY_NAMED_IAM
workflows:
  my_workflow:
    jobs:
      - setupCLI
