version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

executor:
  name: default
  python-version: 3.7.4
jobs:
  setupCLI:
    docker:
      - image: amazon/aws-cli
    steps:
      - aws-cli/install
      - run:
          command: |
            aws configure set aws_access_key_id \
              $AWS_ACCESS_KEY_ID \
              --profile augusto-circleCI
          name: Configure AWS Access Key ID
      - run:
          command: |
            aws configure set aws_secret_access_key \
              $AWS_SECRET_ACCESS_KEY \
              --profile augusto-circleCI
          name: Configure AWS Secret Access Key
      - checkout
      # - run:
      #     name: Create AWS Stack
      #     command: |
      #       aws cloudformation deploy \
      #         --template template.yml \
      #         --stack-name my-stack \
      #         --region=us-west-2 \
      #         --capabilities CAPABILITY_NAMED_IAM
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["b5:d7:f7:e3:fc:ad:81:0d:d0:1e:e5:e9:03:36:b0:d3"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
workflows:
  my_workflow:
    jobs:
      - setupCLI
      - configure_infrastructure:
          requires:
            - setupCLI
