version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

# jobs:
#   aws-cli:
#     executor: aws-cli/default
#     steps:
#       - checkout
#       - aws-cli/setup:
#           profile-name: AugustoRamos
#   create_infrastructure:
#     docker:
#       - image: amazon/aws-cli
#     steps:
#       - checkout
#       - run:
#           name: Ensure backend infrastructure exist
#           command: |
#             aws cloudformation deploy \
#               --template-file template.yml \
#               --stack-name my-stack \
#               --region=us-west-2
#               --aws-access-key-id $AWS_ACCESS_KEY_ID
#               --aws-secret-access-key $AWS_SECRET_ACCESS_KEY
#               --capabilities CAPABILITY_NAMED_IAM
# workflows:
#   my_workflow:
#     jobs:
#       - aws-cli
#       - create_infrastructure

executor:
  name: default
  python-version: 3.7.4
steps:
  - aws-cli/install
  - aws-cli/configure:
      aws-access-key-id: AWS_SECRET_ACCESS_KEY
      aws-region: us-west-2
      aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      configure-default-region: us-west-2
      profile-name: augusto-circleCI
  - checkout
  - deploy:
      capabilities: CAPABILITY_NAMED_IAM
      stack-name: my_stack
      template-file-path: template.yml
