version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

executor:
  name: default
  python-version: 3.7.4
jobs:
  setupCLI:
    docker:
      - image: amazon/aws-cli
    steps:
      - aws-cli/install
      - run:
          command: |
            aws configure set aws_access_key_id \
              $AWS_ACCESS_KEY_ID \
              --profile augusto-circleCI
          name: Configure AWS Access Key ID
      - run:
          command: |
            aws configure set aws_secret_access_key \
              $AWS_SECRET_ACCESS_KEY \
              --profile augusto-circleCI
          name: Configure AWS Secret Access Key
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack \
              --region=us-west-2 \
              --capabilities CAPABILITY_NAMED_IAM
workflows:
  my_workflow:
    jobs:
      - setupCLI
